#!/usr/bin/env python3
"""Wizarch theme registry and transactional local theme application."""
import json, os, re, subprocess, sys, tempfile
from pathlib import Path
BASE=Path(__file__).resolve().parents[1]
HYPR=Path.home()/'.config/hypr/wizarch-theme.lua'

def atomic(path,text):
    path.parent.mkdir(parents=True,exist_ok=True)
    fd,tmp=tempfile.mkstemp(dir=path.parent,prefix='.'+path.name)
    try:
        with os.fdopen(fd,'w') as f: f.write(text)
        os.replace(tmp,path)
    finally:
        if os.path.exists(tmp): os.unlink(tmp)

def read_theme(id):
    if not re.fullmatch(r'[a-z0-9-]+',id): raise ValueError('Invalid theme name')
    folder=BASE/'themes'/id
    t=json.loads((folder/'theme.json').read_text())
    if t['id']!=id or not isinstance(t['name'],str) or not isinstance(t['description'],str): raise ValueError('Invalid theme metadata')
    required = set(re.findall(r'palette\.(\w+)', (BASE/'core/Theme.qml').read_text()))
    if not required.issubset(t['colors']): raise ValueError('Theme is missing required Material roles')
    for value in t['colors'].values():
        if not re.fullmatch(r'#[0-9a-fA-F]{6}',value): raise ValueError('Invalid palette')
    for key in ('wallpaper','logo'):
        asset=(folder/t['assets'][key]).resolve()
        if not asset.is_relative_to(folder.resolve()) or not asset.is_file(): raise ValueError('Missing or unsafe theme asset')
        t[key]=asset.as_uri()
    h=t['hyprland']
    if not 0<=h['rounding']<=30 or not 1<=h['borderSize']<=5: raise ValueError('Invalid geometry')
    for k in ['activeBorder','inactiveBorder']:
        if not re.fullmatch(r'#[0-9a-fA-F]{6}',h[k]): raise ValueError('Invalid border color')
    return t

def available_themes():
    themes=[]
    for path in sorted((BASE/'themes').glob('*/theme.json')):
        try:
            themes.append(read_theme(path.parent.name))
        except (OSError, ValueError, KeyError):
            # An optional theme may be missing a locally supplied asset.
            continue
    return themes

def apply(id,live=True):
    t=read_theme(id);h=t['hyprland'];state=BASE/'state/active.json'
    lua='-- Generated by Wizarch; edit the selected theme manifest instead.\nhl.config({ general = { border_size = %d, col = { active_border = { colors = {"rgba(%sff)"}, angle = 0 }, inactive_border = "rgba(%sff)" } }, decoration = { rounding = %d } })\n'%(h['borderSize'],h['activeBorder'][1:],h['inactiveBorder'][1:],h['rounding'])
    old={p:p.read_bytes() if p.exists() else None for p in [state,HYPR]}
    try:
        atomic(HYPR,lua)
        if live:
            subprocess.run(['hyprctl','reload'],check=True,stdout=subprocess.PIPE,stderr=subprocess.PIPE,timeout=5)
            errors=subprocess.check_output(['hyprctl','configerrors'],text=True,timeout=5).strip()
            if errors: raise RuntimeError('Hyprland rejected theme: '+errors[:150])
        atomic(state,json.dumps(t,indent=2))
    except Exception:
        for p,v in old.items():
            if v is None: p.unlink(missing_ok=True)
            else: atomic(p,v.decode())
        if live: subprocess.run(['hyprctl','reload'],stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
        raise
    return {'ok':True,'theme':id}

if __name__=='__main__':
    try:
        if sys.argv[1]=='list': print(json.dumps(available_themes()))
        elif sys.argv[1] in ('apply','init'): print(json.dumps(apply(sys.argv[2],sys.argv[1]=='apply')))
        else: raise ValueError('Use list, apply ID, or init ID')
    except Exception as e:
        print(json.dumps({'ok':False,'error':str(e)}));sys.exit(1)
